function Hf=hessianTensor_testDyn2(x,u)



 out = funOptimize(x,u);



 Hf{1} = sparse(6,6);



 Hf{2} = sparse(6,6);



 Hf{3} = sparse(6,6);

Hf{3}(1,1) = out(1);
Hf{3}(2,1) = out(2);
Hf{3}(1,2) = out(3);
Hf{3}(2,2) = out(4);


 Hf{4} = sparse(6,6);

Hf{4}(1,1) = out(5);
Hf{4}(2,1) = out(6);
Hf{4}(1,2) = out(7);
Hf{4}(2,2) = out(8);


 Hf{5} = sparse(6,6);

function out = funOptimize(in1,uL1R)
%FUNOPTIMIZE
%    OUT = FUNOPTIMIZE(IN1,UL1R)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    04-Aug-2021 12:38:41

xL1R = in1(1,:);
xL2R = in1(2,:);
t2 = xL1R.*2.0;
t3 = xL2R.^2;
t5 = xL1R+4.2164e+7;
t10 = xL1R.*1.43496e+18;
t4 = -t3;
t6 = t5.^2;
t7 = t2+8.4328e+7;
t15 = t10+6.050365344e+25;
t8 = t7.^2;
t9 = t4+t6;
t11 = 1.0./t9.^(5.0./2.0);
t12 = 1.0./t9.^(7.0./2.0);
t13 = t11.*xL2R.*4.30488e+18;
t16 = t7.*t11.*2.15244e+18;
t17 = t3.*t7.*t12.*1.07622e+19;
t18 = t11.*t15.*3.0;
t19 = t7.*t12.*t15.*xL2R.*(1.5e+1./2.0);
t14 = -t13;
t20 = t16+t17;
t21 = t14+t19;
out = [t18+t7.*t11.*4.30488e+18-t8.*t12.*t15.*(1.5e+1./4.0);t21;t21;-t18-t3.*t12.*t15.*1.5e+1;t13-t8.*t12.*xL2R.*5.3811e+18;t20;t20;t11.*xL2R.*-1.291464e+19-t12.*xL2R.^3.*2.15244e+19];
